const mockEvents = {
    city: {
        id: 1007700,
        city: 'München',
        lat: 48.14,
        lon: 11.58,
        state: '',
        country: 'de',
        zip: 'meetup3',
        member_count: 1257
    },
    events: [
        {
            local_time: '19:00',
            local_date: '2020-03-10',
            link: 'https://www.meetup.com/Munich-Girl-Gone-International/events/268347838/',
            visibility: 'public_limited',
            group: {
                created: 1380914527000,
                name: 'Munich | Girl Gone International',
                id: 10552542,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Girl-Gone-International',
                who: 'Girls Gone International',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 0,
            yes_rsvp_count: 2,
            duration: 7200000,
            time: 1583863200000,
            utc_offset: 3600000,
            name: 'GGI Book Club - March: A Room of One\'s Own and We Should All be Feminists',
            id: '268347838'
        },
        {
            local_time: '19:00',
            local_date: '2020-02-28',
            link: 'https://www.meetup.com/munichmingle/events/268322102/',
            visibility: 'public_limited',
            group: {
                created: 1552581049000,
                name: 'Munich Mingle',
                id: 31389319,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'munichmingle',
                who: 'members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 0,
            yes_rsvp_count: 4,
            duration: 7200000,
            time: 1582912800000,
            utc_offset: 3600000,
            name: '👥 Speed-Friending with an ice-breaker app',
            id: '268322102'
        },
        {
            local_time: '19:00',
            local_date: '2020-03-06',
            link: 'https://www.meetup.com/social-drinks-munich/events/swsnnrybcfbjb/',
            visibility: 'public_limited',
            group: {
                created: 1557680536000,
                name: 'Social Drinks Munich - Make New Friends 😊 🍻🍷🍾🎉',
                id: 31885488,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'social-drinks-munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 0,
            yes_rsvp_count: 3,
            duration: 21600000,
            time: 1583517600000,
            utc_offset: 3600000,
            name: 'Social Drinks Munich - Make New Friends (FREE INTL EVENT) 😊 🍻🍾🎉',
            id: 'swsnnrybcfbjb'
        },
        {
            created: 1580867064000,
            duration: 7200000,
            id: 'gssrnrybcdbsb',
            name: 'Co-Dinner: Good Food & Sociability',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581703200000,
            local_date: '2020-02-14',
            local_time: '19:00',
            updated: 1580867064000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 26846459,
                name: 'togather ',
                lat: 48.137943267822266,
                lon: 11.543676376342773,
                repinned: false,
                address_1: 'Schwanthalerstraße 160',
                city: 'München ',
                country: 'DE',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1538836714000,
                name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
                id: 30090989,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Co-Dining',
                who: 'Netzwerkerinnen und Netzwerker',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Co-Dining/events/gssrnrybcdbsb/',
            description: '<p>Liebe Netzwerker und Netzwerkerinnen,</p> <p>den Abend in geselliger Runde mit anderen verbringen. Gute hausgemachte Küche genießen und dabei mit netten Leuten ins Gespräch kommen.</p> <p>Jeder bezahlt das was er bestellt, gute Laune, eine tolle Atmosphäre und ein herzliches Miteinander schenken wir uns gegenseitig.</p> <p>Ich freue mich wenn du dabei bist und ich dich im togather begrüßen kann.</p> <p>Bis Freitagabend!</p> ',
            how_to_find_us: 'dreieckiger Tisch in der Mitte',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1575032055000,
            duration: 5400000,
            id: 'vhmvnrybcfbqb',
            name: 'Meet&Read Buchclub für B1/B2/C1 ',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1584033300000,
            local_date: '2020-03-12',
            local_time: '18:15',
            updated: 1581244001000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 5,
            venue: {
                id: 26190270,
                name: 'Edeltraud Mitte',
                lat: 48.13649368286133,
                lon: 11.55813980102539,
                repinned: true,
                address_1: 'Landwehrstraße 44',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1493907703000,
                name: 'German Conversation Club Munich',
                id: 23587093,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'German-Conversation-Club-Munich',
                who: 'German Clubbers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/German-Conversation-Club-Munich/events/vhmvnrybcfbqb/',
            how_to_find_us: 'Eingang über Landwehrstr. 44, das Sprachzentrum ist im Hinterhaus. Enter through Landwehrstr. 44, the language center is at the back.',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1580634450000,
            duration: 7200000,
            id: 'dmvpnrybcdbqb',
            name: 'English Meeting - Cafe Westend',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581530400000,
            local_date: '2020-02-12',
            local_time: '19:00',
            updated: 1580634450000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 12,
            venue: {
                id: 26178167,
                name: 'Cafe Westend Gaststättenbetriebs GmbH',
                lat: 48.132266998291016,
                lon: 11.539331436157227,
                repinned: false,
                address_1: 'Ganghoferstraße 50',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1578819345000,
                name: 'English Meeting',
                id: 33193691,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'meetup-group-NvSyMdxj',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/meetup-group-NvSyMdxj/events/dmvpnrybcdbqb/',
            description: '<p>As mentioned in the group description, the event usually takes place at the Cafe Westend near the Schwanthalerhöhe in Munich.</p> <p>The event kicks off around 7PM and, depending on the atmosphere, people usually hang around until 9PM.</p> <p>Usually there\'s a crowed of 8-14 people, and I hope you\'ll be among them.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1580903694000,
            duration: 3600000,
            id: '268475531',
            name: 'Wanted Part-time Hosts/Organisers (Generous expenses paid!)',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581890400000,
            local_date: '2020-02-16',
            local_time: '23:00',
            updated: 1580903799000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 2,
            group: {
                created: 1573235863000,
                name: 'Munich New in the city Meetup',
                id: 32991517,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-New-in-the-city-Meetup',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munich-New-in-the-city-Meetup/events/268475531/',
            description: '<p>(Please be aware that this is an announcement and not a meetup plan. If you would like to host meetups then please get in touch via whatsapp at the details below)</p> <p>Sophia, Delphine and Anya are our regular community manager in Munich! However, sometimes they get busy with work so we would like to have an additional host for Munich.</p> <p>If you would like to HOST meetups, get experience with different cultures whilst making new friends and also get a generous expenses allowance then please get in touch.</p> <p>Are you a people person? Do you love to go out, plan and organize events, meet new people and help people connect with each other?</p> <p>If you can relate to this then we may have the perfect opportunity for YOU! The cherry on the top is that you get great experience, learn new skills, rapidly expand your own network and you get paid an expense allowance for doing something you LOVE to do!</p> <p>Kindly note: This is a voluntary part-time role with an expense allowance (this is not employment) of about 3 to 5 hours a month.</p> <p>This role is a great start for someone who has taken a break from work, just moved into the city, someone who needs to network for their main occupation or just for someone who is socially confident and loves meeting people!</p> <p>This is also a wonderful opportunity for self development since organising gives you great insight into human psychology, group dynamics, strategy and event management. It also makes you the social leader of the group and enables you to rapidly expand your network.</p> <p>Here’s the offer:-</p> <p>We have over 525,000 members in 32 cities around the world with over 150 meetup groups and you can become a part of our rapidly growing team as a host/organizer in your city.</p> <p>You’ll be hosting our drinks, socialising evenings and also some activity events for our groups.</p> <p>If you are up for this extremely satisfying yet challenging role then get in touch with Dan -</p> <p>**Whatsapp or text on [masked]**</p> <p>Look forward to hearing from you!</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1580468242000,
            duration: 10800000,
            id: '268348914',
            name: 'Wine and Cheese day',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1582221600000,
            local_date: '2020-02-20',
            local_time: '19:00',
            updated: 1580468242000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 19,
            group: {
                created: 1434007980000,
                name: 'München Wine Tasting Club',
                id: 18664929,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-Wine-Tasting-Club',
                who: 'München Wine Tasters',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munchen-Wine-Tasting-Club/events/268348914/',
            description: '<p>Wine and Cheese such a wonderful reason to get together.</p> <p>Once a month, we are meeting to drink wine with great pairing cheeses.<br/>With every sort of wine, you will get a chance to try a pairing cheese.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579083777000,
            duration: 10800000,
            id: '267930293',
            name: 'Valentine\'s Meet Mix & Mingle - Ladies & Gents! (21-45)(FREE Drink/Hosted)',
            rsvp_limit: 100,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581789600000,
            local_date: '2020-02-15',
            local_time: '19:00',
            updated: 1579175443000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 34,
            venue: {
                id: 26087176,
                name: 'The Keg Bar',
                lat: 48.158103942871094,
                lon: 11.585509300231934,
                repinned: false,
                address_1: 'Trautenwolfstraße 1',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1573235863000,
                name: 'Munich New in the city Meetup',
                id: 32991517,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-New-in-the-city-Meetup',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munich-New-in-the-city-Meetup/events/267930293/',
            how_to_find_us: 'Please ask for Meetup/DELPHINE',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1580409764000,
            duration: 5400000,
            fee: {
                accepts: 'paypal',
                amount: 20,
                currency: 'EUR',
                description: '',
                label: 'Price',
                required: true
            },
            id: '268325678',
            name: 'Weg mit dem Stress! 90 Min. Workshop für einen entspannten Alltag',
            rsvp_limit: 8,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583861400000,
            local_date: '2020-03-10',
            local_time: '18:30',
            updated: 1580470728000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26589310,
                name: 'Studio 148 - Ausatmen. Einatmen.',
                lat: 48.151973724365234,
                lon: 11.561727523803711,
                repinned: true,
                address_1: 'Theresienstraße 148',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1514739324000,
                name: 'Alpen Yoga München. Yoga, Wandern & Entspannen!',
                id: 27011417,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen/events/268325678/',
            how_to_find_us: 'Wir sind im unteren Raum. ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579523052000,
            duration: 10800000,
            id: '268057257',
            name: 'Meet new friends - like-minded ladies & gents! (21-45)(FREE Drink/Hosted)',
            rsvp_limit: 100,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1582999200000,
            local_date: '2020-02-29',
            local_time: '19:00',
            updated: 1579523249000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 7,
            venue: {
                id: 26087176,
                name: 'The Keg Bar',
                lat: 48.158103942871094,
                lon: 11.585509300231934,
                repinned: false,
                address_1: 'Trautenwolfstraße 1',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1474915787000,
                name: 'Munich Singles Club Meetup (4500+ singles)',
                id: 20477037,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'meetup-groupmunichsingles',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/meetup-groupmunichsingles/events/268057257/',
            how_to_find_us: 'Please ask for Meetup/DELPHINE',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1578127407000,
            duration: 7200000,
            id: 'tsjmnrybcfbhc',
            name: 'Restaurant hopping',
            rsvp_limit: 20,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1585159200000,
            local_date: '2020-03-25',
            local_time: '19:00',
            updated: 1580296762000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 5,
            group: {
                created: 1578072802000,
                name: 'Foodtour - Foodies are welcome to hop through restaurants',
                id: 33160683,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Foodtour-Foodies-are-welcome-to-hop-through-restaurants',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Foodtour-Foodies-are-welcome-to-hop-through-restaurants/events/tsjmnrybcfbhc/',
            description: '<p>If you cannot attend, please opt out so others get a chance to meetup.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1578727922000,
            duration: 10800000,
            id: '267828256',
            name: 'Valentine\'s Day Special - Meet single ladies & gents! (FREE Drink/Hosted)',
            rsvp_limit: 100,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581699600000,
            local_date: '2020-02-14',
            local_time: '18:00',
            updated: 1578739951000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 61,
            venue: {
                id: 26752537,
                name: 'Irish Pub Dubliner',
                lat: 48.13801956176758,
                lon: 11.579821586608887,
                repinned: true,
                address_1: 'Platzl 2',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1573235863000,
                name: 'Munich New in the city Meetup',
                id: 32991517,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-New-in-the-city-Meetup',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munich-New-in-the-city-Meetup/events/267828256/',
            how_to_find_us: 'Area reserved for Meetup / SOPHIA ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            local_time: '19:00',
            local_date: '2020-03-04',
            link: 'https://www.meetup.com/munichmingle/events/268544023/',
            visibility: 'public_limited',
            group: {
                created: 1552581049000,
                name: 'Munich Mingle',
                id: 31389319,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'munichmingle',
                who: 'members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 0,
            yes_rsvp_count: 2,
            duration: 10800000,
            time: 1583344800000,
            utc_offset: 3600000,
            name: '🎲 Game Night | games provided | 1 free drink',
            id: '268544023'
        },
        {
            created: 1576934209000,
            duration: 7200000,
            id: '267338743',
            name: 'ArtMasters - Painting Party - Gondeln am Meer inkl. ein Glas Sekt zur Begrüßung',
            rsvp_limit: 25,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581444000000,
            local_date: '2020-02-11',
            local_time: '19:00',
            updated: 1576934209000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26033912,
                name: 'Park Café',
                lat: 48.1423454284668,
                lon: 11.56462287902832,
                repinned: false,
                address_1: 'Sophienstraße 7',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1484914984000,
                name: 'ArtMasters Munich - Painting Party',
                id: 21997238,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'artmasters-munich',
                who: 'Jungkünstler',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/artmasters-munich/events/267338743/',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579032102000,
            duration: 9000000,
            id: '267913583',
            name: 'ArtMasters - Painting Party - Starry Night inkl. ein Glas Sekt',
            rsvp_limit: 25,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1585674000000,
            local_date: '2020-03-31',
            local_time: '19:00',
            updated: 1579032102000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26033912,
                name: 'Park Café',
                lat: 48.1423454284668,
                lon: 11.56462287902832,
                repinned: true,
                address_1: 'Sophienstraße 7',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1484914984000,
                name: 'ArtMasters Munich - Painting Party',
                id: 21997238,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'artmasters-munich',
                who: 'Jungkünstler',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/artmasters-munich/events/267913583/',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581106167000,
            duration: 7200000,
            id: '268542489',
            name: 'Birds of prey',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581527100000,
            local_date: '2020-02-12',
            local_time: '18:05',
            updated: 1581106167000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 2,
            venue: {
                id: 26252833,
                name: 'Museum Lichtspiele',
                lat: 48.1309700012207,
                lon: 11.587413787841797,
                repinned: false,
                address_1: 'Lilienstraße 2',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1477399931000,
                name: 'Munich Movies OV (English/FRA/ES/HU/...) Meetup',
                id: 20899359,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Movies-OV-English-Meetup',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munich-Movies-OV-English-Meetup/events/268542489/',
            how_to_find_us: 'I will not join this meetup, cool kids go on Sundays ;p Please connect here in the comment section, or meet at the Bar at the corners (Rosi\'s). Enjoy...',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1575032055000,
            duration: 5400000,
            id: 'vhmvnrybcfbjc',
            name: 'Meet&Read Buchclub für B1/B2/C1 ',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1585242900000,
            local_date: '2020-03-26',
            local_time: '18:15',
            updated: 1581244001000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 4,
            venue: {
                id: 26190270,
                name: 'Edeltraud Mitte',
                lat: 48.13649368286133,
                lon: 11.55813980102539,
                repinned: true,
                address_1: 'Landwehrstraße 44',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1493907703000,
                name: 'German Conversation Club Munich',
                id: 23587093,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'German-Conversation-Club-Munich',
                who: 'German Clubbers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/German-Conversation-Club-Munich/events/vhmvnrybcfbjc/',
            how_to_find_us: 'Eingang über Landwehrstr. 44, das Sprachzentrum ist im Hinterhaus. Enter through Landwehrstr. 44, the language center is at the back.',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581031033000,
            duration: 10800000,
            id: '268519015',
            name: 'Chinesisch - Deutscher Treff  慕尼黑的中德语言角',
            rsvp_limit: 14,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1582133400000,
            local_date: '2020-02-19',
            local_time: '18:30',
            updated: 1581031033000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26150135,
                name: 'Coffee Fellows',
                lat: 48.1400260925293,
                lon: 11.56225872039795,
                repinned: false,
                address_1: 'Schützenstraße 14',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1562189025000,
                name: 'Chinesisch - Deutsche Ecke München  慕尼黑的中德语言角',
                id: 32314783,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Chinesisch-Deutsche-Ecke-Muenchen',
                who: 'Freunde / 朋友',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Chinesisch-Deutsche-Ecke-Muenchen/events/268519015/',
            description: '<p>Es ist Mittwoch, lass uns abends zusammen was unternehmen. Ort: Coffee Fellows, Schützenstr. 14, 80335 München. Zur besseren Planung bitten wir um eine verbindliche Zusage. Absagen bitte rechtzeitig mitteilen.<br/>来了来了，让我们相聚起来，聊德語，讲中文。<br/>地址: Coffee Fellows, Schützenstr. 14, 80335 München。为了更好地规划，我们要求作出有约束力的承诺。不能到场的朋友请及時取消。谢谢。</p> ',
            how_to_find_us: 'Coffee Fellows, Schützenstr. 14, 80335 München',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            local_time: '20:00',
            local_date: '2020-02-14',
            link: 'https://www.meetup.com/social-drinks-munich/events/nfkpnrybcdbsb/',
            visibility: 'public_limited',
            group: {
                created: 1557680536000,
                name: 'Social Drinks Munich - Make New Friends 😊 🍻🍷🍾🎉',
                id: 31885488,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'social-drinks-munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 0,
            yes_rsvp_count: 27,
            duration: 19800000,
            time: 1581706800000,
            utc_offset: 3600000,
            name: 'Social Drinks Munich - Make New Friends (INTL FREE EVENT) 😊 🍻🍾🎉',
            id: 'nfkpnrybcdbsb'
        },
        {
            local_time: '19:00',
            local_date: '2020-02-21',
            link: 'https://www.meetup.com/social-drinks-munich/events/swsnnrybcdbcc/',
            visibility: 'public_limited',
            group: {
                created: 1557680536000,
                name: 'Social Drinks Munich - Make New Friends 😊 🍻🍷🍾🎉',
                id: 31885488,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'social-drinks-munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 0,
            yes_rsvp_count: 4,
            duration: 21600000,
            time: 1582308000000,
            utc_offset: 3600000,
            name: 'Social Drinks Munich - Make New Friends (FREE INTL EVENT) 😊 🍻🍾🎉',
            id: 'swsnnrybcdbcc'
        },
        {
            local_time: '19:00',
            local_date: '2020-02-19',
            link: 'https://www.meetup.com/nostigmas-munich/events/zfbwmrybcdbzb/',
            visibility: 'public_limited',
            group: {
                created: 1471258175000,
                name: 'NoStigmas Munich',
                id: 20316964,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'nostigmas-munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            waitlist_count: 1,
            yes_rsvp_count: 15,
            duration: 10800000,
            time: 1582135200000,
            utc_offset: 3600000,
            name: 'No Stigmas monthly meetup',
            id: 'zfbwmrybcdbzb'
        },
        {
            created: 1575032055000,
            duration: 5400000,
            id: 'vhmvnrybcdbkc',
            name: 'Meet&Read Buchclub für B1/B2/C1 ',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1582823700000,
            local_date: '2020-02-27',
            local_time: '18:15',
            updated: 1581244001000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 9,
            venue: {
                id: 26190270,
                name: 'Edeltraud Mitte',
                lat: 48.13649368286133,
                lon: 11.55813980102539,
                repinned: true,
                address_1: 'Landwehrstraße 44',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1493907703000,
                name: 'German Conversation Club Munich',
                id: 23587093,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'German-Conversation-Club-Munich',
                who: 'German Clubbers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/German-Conversation-Club-Munich/events/vhmvnrybcdbkc/',
            how_to_find_us: 'Eingang über Landwehrstr. 44, das Sprachzentrum ist im Hinterhaus. Enter through Landwehrstr. 44, the language center is at the back.',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579696976000,
            duration: 4500000,
            fee: {
                accepts: 'paypal',
                amount: 60,
                currency: 'EUR',
                description: '',
                label: 'Price',
                required: true
            },
            id: '268110411',
            name: 'Yoga-Kurs für Einsteiger! 4x75 Min. Basic Vinyasa Flow',
            rsvp_limit: 15,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1586271600000,
            local_date: '2020-04-07',
            local_time: '17:00',
            updated: 1579696976000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26589310,
                name: 'Studio 148 - Ausatmen. Einatmen.',
                lat: 48.151973724365234,
                lon: 11.561727523803711,
                repinned: false,
                address_1: 'Theresienstraße 148',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1514739324000,
                name: 'Alpen Yoga München. Yoga, Wandern & Entspannen!',
                id: 27011417,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen/events/268110411/',
            how_to_find_us: 'Wir sind im oberen Raum',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581035005000,
            duration: 7200000,
            id: '268520176',
            name: 'Chinesisch & Deutsch lernen mit Duolingo  - 用多邻国学习汉语和德语',
            rsvp_limit: 14,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583067600000,
            local_date: '2020-03-01',
            local_time: '14:00',
            updated: 1581035088000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26150135,
                name: 'Coffee Fellows',
                lat: 48.1400260925293,
                lon: 11.56225872039795,
                repinned: true,
                address_1: 'Schützenstraße 14',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1562189025000,
                name: 'Chinesisch - Deutsche Ecke München  慕尼黑的中德语言角',
                id: 32314783,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Chinesisch-Deutsche-Ecke-Muenchen',
                who: 'Freunde / 朋友',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Chinesisch-Deutsche-Ecke-Muenchen/events/268520176/',
            description: '<p>Lasst uns gemeinsam Deutsch und Chinesisch lernen - mit Hilfe der App Duolingo. Bringt Euer Notebook und Headset mit. Ort: Coffee Fellows, Schützenstr. 14, 80335 München. Zur besseren Planung bitten wir um eine verbindliche Zusage. Absagen bitte rechtzeitig mitteilen.</p> <p>让我们使用Duolingo应用程序一起学习德语和中文-请携带笔记本和耳机。<br/>地址: Coffee Fellows, Schützenstr. 14, 80335 München。为了更好地规划，我们要求作出有约束力的承诺。不能到场的朋友请及時取消。谢谢。</p> ',
            how_to_find_us: 'Coffee Fellows, Schützenstr. 14, 80335 München',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579031992000,
            duration: 9000000,
            id: '267913547',
            name: 'ArtMasters - Painting Party - Starry Night inkl. ein Glas Sekt',
            rsvp_limit: 25,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1583085600000,
            local_date: '2020-03-01',
            local_time: '19:00',
            updated: 1579031992000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 26033912,
                name: 'Park Café',
                lat: 48.1423454284668,
                lon: 11.56462287902832,
                repinned: false,
                address_1: 'Sophienstraße 7',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1484914984000,
                name: 'ArtMasters Munich - Painting Party',
                id: 21997238,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'artmasters-munich',
                who: 'Jungkünstler',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/artmasters-munich/events/267913547/',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1580916896000,
            duration: 7200000,
            id: '268479283',
            name: 'Portuguese wine tasting - charity event ',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581958800000,
            local_date: '2020-02-17',
            local_time: '18:00',
            updated: 1580917710000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 10,
            venue: {
                id: 26847267,
                name: 'Der Pschorr – das bayerische Wirtshaus am Viktualienmarkt',
                lat: 48.13481521606445,
                lon: 11.575152397155762,
                repinned: true,
                address_1: 'Viktualienmarkt 15',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1547990765000,
                name: 'München Wine, Food & Friends',
                id: 30968717,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-Wine-Food-Friends',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munchen-Wine-Food-Friends/events/268479283/',
            how_to_find_us: 'at the location - 2nd floor event room',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1578127407000,
            duration: 7200000,
            id: 'tsjmnrybcdbjc',
            name: 'Restaurant hopping',
            rsvp_limit: 20,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1582740000000,
            local_date: '2020-02-26',
            local_time: '19:00',
            updated: 1580296761000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 9,
            group: {
                created: 1578072802000,
                name: 'Foodtour - Foodies are welcome to hop through restaurants',
                id: 33160683,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Foodtour-Foodies-are-welcome-to-hop-through-restaurants',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Foodtour-Foodies-are-welcome-to-hop-through-restaurants/events/tsjmnrybcdbjc/',
            description: '<p>If you cannot attend, please opt out so others get a chance to meetup.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579605665000,
            duration: 3600000,
            fee: {
                accepts: 'paypal',
                amount: 15,
                currency: 'EUR',
                description: '',
                label: 'Price',
                required: true
            },
            id: '268082627',
            name: '60 Min. Yoga für Kraft & Gelassenheit! Spiritual Warrior Flow',
            rsvp_limit: 6,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1582651800000,
            local_date: '2020-02-25',
            local_time: '18:30',
            updated: 1579605665000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26589310,
                name: 'Studio 148 - Ausatmen. Einatmen.',
                lat: 48.151973724365234,
                lon: 11.561727523803711,
                repinned: true,
                address_1: 'Theresienstraße 148',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1514739324000,
                name: 'Alpen Yoga München. Yoga, Wandern & Entspannen!',
                id: 27011417,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen/events/268082627/',
            how_to_find_us: 'Wir sind im unteren Raum',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1580680570000,
            duration: 5400000,
            id: '268409411',
            name: 'Co-Lunch: Neue Kontakte in der Mittagspause',
            rsvp_limit: 17,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1581679800000,
            local_date: '2020-02-14',
            local_time: '12:30',
            updated: 1580680570000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 26822176,
                name: 'togather',
                lat: 48.137943267822266,
                lon: 11.543676376342773,
                repinned: true,
                address_1: 'Schwanthalerstraße 160',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            group: {
                created: 1538836714000,
                name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
                id: 30090989,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Co-Dining',
                who: 'Netzwerkerinnen und Netzwerker',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Co-Dining/events/268409411/',
            description: '<p>WAS IST CO-LUNCH</p> <p>Das Co-Lunch ist wie immer dazu da, die Mittagspause zu nutzen um neue Leute kennen zu lernen und beruflich oder privat zu Netzwerken. Hol dir frische Motivation und Inspiration in deiner Lunch Break.<br/>Wonach auch immer dir an diesem Tag, zu dieser Stunde ist, sei ruhig, sei laut, erzähle oder höre zu. Komm aus dich raus oder genieße dein Essen an der großen Tafel. Alles darf sein. Jeder ist willkommen. Sei neugierig, wer heute mit am Tisch sitzt.</p> <p>Jeder kommt für den eigenen Verzehr auf.</p> <p>Bitte sagt ab, falls ihr es nicht schafft zu kommen.</p> <p>-------------------------------------english------------------------------------<br/>Why not using the lunch break to meet new inspiring people, to make new business contacts and broaden your network.<br/>I like to meet others who appreciate the idea of socializing, networking and having a quality time at lunch. A perfect lunch break for me is an empowering break in the middle of the day, which gives me energy and motivation for the second half of the day. Lets have lunch together.</p> <p>Agenda:<br/>There is no such thing like an agenda. Everbody will have the opportunitiy to introduce himself. There should be room to embrace yourself, to listen to others, to ask and to answer. Be kind to another, get inspired and motivate each other for a better life.</p> <p>Looking forward to see you soon.</p> <p>1st note: Kindly only sign up, if you can really make it. Please cancel your reservation if you cannot appear.</p> <p>2nd note: Everbody pays for his or her own consumption.</p> <p>Bis bald and see you soon,<br/>Eure Sarah</p> ',
            how_to_find_us: 'Meetup Tisch in der Mitte',
            visibility: 'public',
            member_pay_fee: false
        }
    ]
}

export { mockEvents };